huateng_camera_node:
  ros__parameters:
    camera_id: 0
    width: 640
    height: 480
    fps: 30
    output_format: "bgr8"
    param_save_path: "/tmp/huateng_params.bin"
    exposure_time: 10000.0
    exposure_auto: false
