huateng_camera_node:
  ros__parameters:
    camera_id: 0
    width: 1280
    height: 1024
    fps: 60
    output_format: "bgr8"
    param_save_path: "/tmp/huateng_params.bin"
    exposure_time: 3000.0
    exposure_auto: false
